name: Check

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - uses: actions/setup-python@v2
    - run: cargo build --release
    - run: pip install pre-commit
    - run: rustup component add clippy
    - run: pre-commit run --show-diff-on-failure --color=always --all-files
